# Generated by Django 4.1.7 on 2023-03-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id_tableau', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('position_col', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('position_col', models.IntegerField()),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tableau')),
            ],
        ),
    ]
