# Generated by Django 4.1.7 on 2023-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tableau_position_col_alter_task_position_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='position_col',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='position_col',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('tableau', 'position_col')},
        ),
    ]
