# Generated by Django 4.1.7 on 2023-04-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tableau_position_col_alter_task_position_col_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableau',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='tableau',
            old_name='position_col',
            new_name='position',
        ),
    ]
